require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CourseCodesController do

  # This should return the minimal set of attributes required to create a valid
  # CourseCode. As you add validations to CourseCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CourseCodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all course_codes as @course_codes" do
      course_code = CourseCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:course_codes).should eq([course_code])
    end
  end

  describe "GET show" do
    it "assigns the requested course_code as @course_code" do
      course_code = CourseCode.create! valid_attributes
      get :show, {:id => course_code.to_param}, valid_session
      assigns(:course_code).should eq(course_code)
    end
  end

  describe "GET new" do
    it "assigns a new course_code as @course_code" do
      get :new, {}, valid_session
      assigns(:course_code).should be_a_new(CourseCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_code as @course_code" do
      course_code = CourseCode.create! valid_attributes
      get :edit, {:id => course_code.to_param}, valid_session
      assigns(:course_code).should eq(course_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CourseCode" do
        expect {
          post :create, {:course_code => valid_attributes}, valid_session
        }.to change(CourseCode, :count).by(1)
      end

      it "assigns a newly created course_code as @course_code" do
        post :create, {:course_code => valid_attributes}, valid_session
        assigns(:course_code).should be_a(CourseCode)
        assigns(:course_code).should be_persisted
      end

      it "redirects to the created course_code" do
        post :create, {:course_code => valid_attributes}, valid_session
        response.should redirect_to(CourseCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_code as @course_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        CourseCode.any_instance.stub(:save).and_return(false)
        post :create, {:course_code => {}}, valid_session
        assigns(:course_code).should be_a_new(CourseCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CourseCode.any_instance.stub(:save).and_return(false)
        post :create, {:course_code => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested course_code" do
        course_code = CourseCode.create! valid_attributes
        # Assuming there are no other course_codes in the database, this
        # specifies that the CourseCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CourseCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => course_code.to_param, :course_code => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested course_code as @course_code" do
        course_code = CourseCode.create! valid_attributes
        put :update, {:id => course_code.to_param, :course_code => valid_attributes}, valid_session
        assigns(:course_code).should eq(course_code)
      end

      it "redirects to the course_code" do
        course_code = CourseCode.create! valid_attributes
        put :update, {:id => course_code.to_param, :course_code => valid_attributes}, valid_session
        response.should redirect_to(course_code)
      end
    end

    describe "with invalid params" do
      it "assigns the course_code as @course_code" do
        course_code = CourseCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CourseCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => course_code.to_param, :course_code => {}}, valid_session
        assigns(:course_code).should eq(course_code)
      end

      it "re-renders the 'edit' template" do
        course_code = CourseCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CourseCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => course_code.to_param, :course_code => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_code" do
      course_code = CourseCode.create! valid_attributes
      expect {
        delete :destroy, {:id => course_code.to_param}, valid_session
      }.to change(CourseCode, :count).by(-1)
    end

    it "redirects to the course_codes list" do
      course_code = CourseCode.create! valid_attributes
      delete :destroy, {:id => course_code.to_param}, valid_session
      response.should redirect_to(course_codes_url)
    end
  end

end
